### ISSUE TITLE
"Store Benchmark Results" task is broken

### ISSUE THREAD

**Issue by pabloem** [ray-project/ray_beam_runner#46]
Something about storing the outcome for benchmarks is causing failures in the task.

https://github.com/ray-project/ray_beam_runner/actions/runs/3239121252/jobs/5308126444

Any idea of what's going on @wilsonwang371 ?

**Comment by wilsonwang371** [comment]
it looks like a permission issue. does it have anything to do with branch?

**Comment by wilsonwang371** [comment]
I posted a patch #48

**Comment by iasoon** [comment]
Closed by #48

**Comment by iasoon** [comment]
On a second note, this is not fixed - we are not saving the benchmarks results currently.
I think the workflow is failing because it's running from a PR, for which the `GITHUB_TOKEN` has read-only access by default (and I guess we want this, otherwise a PR would overwrite the results from `master`).

I have opened #50 to change this.
